### ISSUE TITLE
basics of main page

### ISSUE THREAD

**Issue by animyrch** [animyrch/dessinIO#9]
Integration of Bootstrap.
Integration of simple canvas.
- Add script for Socket /!\
- Add connection.js after socket

**Comment by animyrch** [comment]
inclure
<script src = "connetion.js">

**Comment by Elw0od** [comment]
Tu peux inclures mon fichiers :
<script src="canvas-manager.js">

**Comment by animyrch** [comment]
<script src='/socket.io/socket.io.js'></script>
